name: go
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Caching modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-aw-${{ hashFiles('**/go.sum') }}

      - name: Get dependencies
        run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            go get -u github.com/onsi/ginkgo/ginkgo
            go get -u github.com/onsi/gomega/...
            go get -u golang.org/x/lint/golint
            go get -u github.com/loongy/covermerge
            go get -u github.com/mattn/goveralls

      - name: Run vetting
        run: |
            cd $GITHUB_WORKSPACE
            export PATH=$PATH:$(go env GOPATH)/bin
            go vet ./...

      - name: Run linting
        run: |
            cd $GITHUB_WORKSPACE
            export PATH=$PATH:$(go env GOPATH)/bin
            go get -u golang.org/x/lint/golint
            golint ./...

      - name: Run multichain infrastructure
        run: |
            source ./infra/.env
            cd $GITHUB_WORKSPACE/infra
            docker-compose up --build bitcoin     \
                                      bitcoincash \
                                      digibyte    \
                                      dogecoin    \
                                      filecoin    \
                                      terra       \
                                      zcash

      - name: Sleep until the nodes are up
        uses: jakejarvis/wait-action@master
        with:
          time: '5m'

      - name: Run tests and report test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            source ./infra/.env
            cd $GITHUB_WORKSPACE
            CI=true ginkgo --v --race --cover --coverprofile coverprofile.out ./...
            covermerge              \
              chain/bitcoin.out     \
              chain/bitcoincash.out \
              chain/digibyte.out    \
              chain/dogecoin.out    \
              chain/ethereum.out    \
              chain/filecoin.out    \
              chain/terra.out       \
              chain/zcash.out       \
              coverprofile.out > coverprofile.out
              goveralls -coverprofile=coverprofile.out -service=github
