name: go
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
        with:
          submodules: recursive

      - name: Caching modules
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-aw-${{ hashFiles('**/go.sum') }}

      - name: Install dependency packages
        run:
          sudo apt-get install mesa-opencl-icd ocl-icd-opencl-dev

      - name: Get dependencies
        run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            go get -u github.com/onsi/ginkgo/ginkgo
            go get -u github.com/onsi/gomega/...
            go get -u golang.org/x/lint/golint
            go get -u github.com/loongy/covermerge
            go get -u github.com/mattn/goveralls

      - name: Run vetting
        run: |
            cd $GITHUB_WORKSPACE/chain/filecoin/filecoin-ffi
            make
            cd $GITHUB_WORKSPACE
            export PATH=$PATH:$(go env GOPATH)/bin
            go vet ./...

      - name: Run linting
        run: |
            cd $GITHUB_WORKSPACE
            export PATH=$PATH:$(go env GOPATH)/bin
            go get -u golang.org/x/lint/golint
            golint ./...

      - name: Run multichain infrastructure (bitcoin)
        run: docker run -d -p 18443:18443 -h 0.0.0.0 \
          --env-file $GITHUB_WORKSPACE/infra/.ci-env rohitnarurkar/multichain_bitcoin
      - name: Run multichain infrastructure (bitcoincash)
        run: docker run -d -p 19443:19443 -h 0.0.0.0 \
          --env-file $GITHUB_WORKSPACE/infra/.ci-env rohitnarurkar/multichain_bitcoincash
      - name: Run multichain infrastructure (digibyte)
        run: docker run -d -p 20443:20443 -h 0.0.0.0 \
          --env-file $GITHUB_WORKSPACE/infra/.ci-env rohitnarurkar/multichain_digibyte
      - name: Run multichain infrastructure (dogecoin)
        run: docker run -d -p 18332:18332 -h 0.0.0.0 \
          --env-file $GITHUB_WORKSPACE/infra/.ci-env rohitnarurkar/multichain_dogecoin
      - name: Run multichain infrastructure (filecoin)
        run: docker run -d -p 1234:1234 -h 0.0.0.0 \
          --env-file $GITHUB_WORKSPACE/infra/.ci-env --name infra_filecoin_1 rohitnarurkar/multichain_filecoin
      - name: Run multichain infrastructure (terra)
        run: docker run -d -p 26657:26657 -h 0.0.0.0 \
          --env-file $GITHUB_WORKSPACE/infra/.ci-env rohitnarurkar/multichain_terra
      - name: Run multichain infrastructure (zcash)
        run: docker run -d -p 18232:18232 -h 0.0.0.0 \
          --env-file $GITHUB_WORKSPACE/infra/.ci-env rohitnarurkar/multichain_zcash

      - name: Sleep until the nodes are up
        uses: jakejarvis/wait-action@master
        with:
          time: '1m'

      - name: Check on docker containers
        run: docker ps -a

      - name: Run tests and report test coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            export PATH=$PATH:$(go env GOPATH)/bin
            source ./infra/.env
            cd $GITHUB_WORKSPACE
            CI=true ginkgo --v --race --cover --coverprofile coverprofile.out ./...
            covermerge              \
              chain/bitcoin.out     \
              chain/bitcoincash.out \
              chain/digibyte.out    \
              chain/dogecoin.out    \
              chain/ethereum.out    \
              chain/filecoin.out    \
              chain/terra.out       \
              chain/zcash.out       \
              coverprofile.out > coverprofile.out
              goveralls -coverprofile=coverprofile.out -service=github
